S02 us07/home desktop
WildCodeSchool/2023-09-PHP-LYON-P3-nom-nom-nom pull request #18
Opened 2023-12-21 22:18 UTC by nickyrasa

2023-12-21 22:20 UTC, plbonnier approved these changes

2023-12-21 22:21 UTC, Thomas-Lunardo approved these changes

2023-12-22 08:43 UTC, StoicFrenchDev requested changes

2023-12-22 08:43 UTC, StoicFrenchDev commented on templates/home/index.html.twig
> +		<a href="#"><img class="w-25" src="{{ asset('/build/images/entree.png')}}"/></a>
You should add the "alt" attribute for accessibility

2023-12-22 08:59 UTC, StoicFrenchDev approved these changes

2023-12-22 08:59 UTC, merged