S01 us04/ingredients
WildCodeSchool/2023-09-PHP-LYON-P3-nom-nom-nom pull request #24
Opened 2024-01-03 18:10 UTC by Aude711

2024-01-03 18:26 UTC, StoicFrenchDev requested changes

2024-01-03 18:26 UTC, StoicFrenchDev commented on templates/ingredient/index.html.twig
> +                    {# <a href="{{ path('app_ingredient_show', {'id': ingredient.id}) }}">détail de la recette</a> #}
Happy New Year

2024-01-03 18:26 UTC, StoicFrenchDev commented on templates/ingredient/index.html.twig
> +    {# <a href="{{ path('app_ingredient_new') }}">Ajouter votre recette</a> #}
Merry Christmas

2024-01-04 04:57 UTC, nickyrasa approved these changes

2024-01-04 08:57 UTC, plbonnier approved these changes

2024-01-04 08:59 UTC, StoicFrenchDev approved these changes

2024-01-04 08:59 UTC, merged