S03 us13 user page
WildCodeSchool/2023-09-PHP-LYON-P3-nom-nom-nom pull request #37
Opened 2024-01-10 21:20 UTC by Thomas-Lunardo

Hello,
This feature is about mailer and user profile page.
Have a good day.
Aude and Thomas

2024-01-10 21:26 UTC, plbonnier approved these changes

2024-01-10 21:26 UTC, nickyrasa approved these changes

2024-01-11 08:42 UTC, StoicFrenchDev requested changes

2024-01-11 08:42 UTC, StoicFrenchDev commented on templates/security/profile.html.twig
> +				<a href="#" type="button" class="btn button-crud mt-4 mb-2" tabindex="-1" role="button" aria-disabled="true">Mes favoris</a>
I don't think the type="button" is correct nor necessary

2024-01-11 10:53 UTC, merged