S05 debug 03
WildCodeSchool/2023-09-PHP-LYON-P3-nom-nom-nom pull request #77
Opened 2024-01-30 19:27 UTC by nickyrasa

2024-01-31 07:56 UTC, plbonnier approved these changes

2024-01-31 08:32 UTC, StoicFrenchDev requested changes
Because of the checkpoint, you are not authorized to fix the code until Friday.

2024-01-31 08:32 UTC, StoicFrenchDev commented on templates/recipe/show.html.twig
> +			<span class="position-absolute heart">{{ component ('FavoriteList', {recipe: recipe}) }}</>
Span tag isn't properly closed

2024-02-02 14:35 UTC, StoicFrenchDev commented
You may resume your work!

2024-02-02 16:17 UTC, closed without merging